spring.application.name=ecommerceShipping

spring.datasource.url=jdbc:mysql://localhost:3306/shippingecommerce
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
